// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currency_pairs.sql

package repository

import (
	"context"
)

const findPairByCode = `-- name: FindPairByCode :one
SELECT id, from_currency, to_currency, polling_interval_seconds, is_active, created_at, updated_at
FROM currency_pairs
WHERE from_currency = $1 AND to_currency = $2 AND is_active = true
`

type FindPairByCodeParams struct {
	FromCurrency string `json:"from_currency"`
	ToCurrency   string `json:"to_currency"`
}

func (q *Queries) FindPairByCode(ctx context.Context, arg FindPairByCodeParams) (CurrencyPair, error) {
	row := q.db.QueryRow(ctx, findPairByCode, arg.FromCurrency, arg.ToCurrency)
	var i CurrencyPair
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.PollingIntervalSeconds,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePairs = `-- name: GetActivePairs :many
SELECT id, from_currency, to_currency, polling_interval_seconds, is_active, created_at, updated_at
FROM currency_pairs
WHERE is_active = true
ORDER BY id
`

func (q *Queries) GetActivePairs(ctx context.Context) ([]CurrencyPair, error) {
	rows, err := q.db.Query(ctx, getActivePairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrencyPair{}
	for rows.Next() {
		var i CurrencyPair
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.PollingIntervalSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPairs = `-- name: GetAllPairs :many
SELECT id, from_currency, to_currency, polling_interval_seconds, is_active, created_at, updated_at
FROM currency_pairs
ORDER BY id
`

func (q *Queries) GetAllPairs(ctx context.Context) ([]CurrencyPair, error) {
	rows, err := q.db.Query(ctx, getAllPairs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CurrencyPair{}
	for rows.Next() {
		var i CurrencyPair
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.PollingIntervalSeconds,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
