// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrencyPair struct {
	ID                     int64              `json:"id"`
	FromCurrency           string             `json:"from_currency"`
	ToCurrency             string             `json:"to_currency"`
	PollingIntervalSeconds int32              `json:"polling_interval_seconds"`
	IsActive               bool               `json:"is_active"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

type PairProviderConfig struct {
	ID             int64              `json:"id"`
	CurrencyPairID int64              `json:"currency_pair_id"`
	ProviderID     int64              `json:"provider_id"`
	Priority       string             `json:"priority"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type Provider struct {
	ID                  int64              `json:"id"`
	Name                string             `json:"name"`
	AdapterType         string             `json:"adapter_type"`
	BaseUrl             string             `json:"base_url"`
	RateJsonPath        pgtype.Text        `json:"rate_json_path"`
	CurrencyCodeMapping []byte             `json:"currency_code_mapping"`
	ApiKey              pgtype.Text        `json:"api_key"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type ProviderHealth struct {
	ID                  int64              `json:"id"`
	ProviderID          int64              `json:"provider_id"`
	CurrencyPairID      int64              `json:"currency_pair_id"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastErrorMessage    pgtype.Text        `json:"last_error_message"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

type Rate struct {
	ID               int64              `json:"id"`
	CurrencyPairID   int64              `json:"currency_pair_id"`
	SourceProviderID int64              `json:"source_provider_id"`
	Rate             pgtype.Numeric     `json:"rate"`
	IsOutdated       bool               `json:"is_outdated"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
