// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pair_provider_config.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getProvidersForPair = `-- name: GetProvidersForPair :many
SELECT
    ppc.id,
    ppc.currency_pair_id,
    ppc.provider_id,
    ppc.priority,
    ppc.is_active,
    ppc.created_at,
    p.name AS provider_name,
    p.adapter_type,
    p.base_url,
    p.rate_json_path,
    p.currency_code_mapping,
    p.api_key
FROM pair_provider_config ppc
         JOIN providers p ON p.id = ppc.provider_id
WHERE ppc.currency_pair_id = $1
  AND ppc.is_active = true
  AND p.is_active = true
ORDER BY
    CASE ppc.priority WHEN 'primary' THEN 0 ELSE 1 END
`

type GetProvidersForPairRow struct {
	ID                  int64              `json:"id"`
	CurrencyPairID      int64              `json:"currency_pair_id"`
	ProviderID          int64              `json:"provider_id"`
	Priority            string             `json:"priority"`
	IsActive            bool               `json:"is_active"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ProviderName        string             `json:"provider_name"`
	AdapterType         string             `json:"adapter_type"`
	BaseUrl             string             `json:"base_url"`
	RateJsonPath        pgtype.Text        `json:"rate_json_path"`
	CurrencyCodeMapping []byte             `json:"currency_code_mapping"`
	ApiKey              pgtype.Text        `json:"api_key"`
}

func (q *Queries) GetProvidersForPair(ctx context.Context, currencyPairID int64) ([]GetProvidersForPairRow, error) {
	rows, err := q.db.Query(ctx, getProvidersForPair, currencyPairID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProvidersForPairRow{}
	for rows.Next() {
		var i GetProvidersForPairRow
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyPairID,
			&i.ProviderID,
			&i.Priority,
			&i.IsActive,
			&i.CreatedAt,
			&i.ProviderName,
			&i.AdapterType,
			&i.BaseUrl,
			&i.RateJsonPath,
			&i.CurrencyCodeMapping,
			&i.ApiKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
