// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: provider_health.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAllHealth = `-- name: GetAllHealth :many
SELECT
    ph.id,
    ph.provider_id,
    ph.currency_pair_id,
    ph.last_success_at,
    ph.last_failure_at,
    ph.consecutive_failures,
    ph.last_error_message,
    ph.updated_at,
    p.name AS provider_name
FROM provider_health ph
         JOIN providers p ON p.id = ph.provider_id
ORDER BY p.name, ph.currency_pair_id
`

type GetAllHealthRow struct {
	ID                  int64              `json:"id"`
	ProviderID          int64              `json:"provider_id"`
	CurrencyPairID      int64              `json:"currency_pair_id"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastErrorMessage    pgtype.Text        `json:"last_error_message"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	ProviderName        string             `json:"provider_name"`
}

func (q *Queries) GetAllHealth(ctx context.Context) ([]GetAllHealthRow, error) {
	rows, err := q.db.Query(ctx, getAllHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllHealthRow{}
	for rows.Next() {
		var i GetAllHealthRow
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.CurrencyPairID,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.ConsecutiveFailures,
			&i.LastErrorMessage,
			&i.UpdatedAt,
			&i.ProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHealthByProvider = `-- name: GetHealthByProvider :many
SELECT id, provider_id, currency_pair_id, last_success_at, last_failure_at, consecutive_failures, last_error_message, updated_at
FROM provider_health
WHERE provider_id = $1
ORDER BY currency_pair_id
`

func (q *Queries) GetHealthByProvider(ctx context.Context, providerID int64) ([]ProviderHealth, error) {
	rows, err := q.db.Query(ctx, getHealthByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderHealth{}
	for rows.Next() {
		var i ProviderHealth
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.CurrencyPairID,
			&i.LastSuccessAt,
			&i.LastFailureAt,
			&i.ConsecutiveFailures,
			&i.LastErrorMessage,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordFailure = `-- name: RecordFailure :exec
INSERT INTO provider_health (provider_id, currency_pair_id, last_failure_at, consecutive_failures, last_error_message, updated_at)
VALUES ($1, $2, now(), 1, $3, now())
ON CONFLICT (provider_id, currency_pair_id)
    DO UPDATE SET
                  last_failure_at      = now(),
                  consecutive_failures = provider_health.consecutive_failures + 1,
                  last_error_message   = $3,
                  updated_at           = now()
`

type RecordFailureParams struct {
	ProviderID       int64       `json:"provider_id"`
	CurrencyPairID   int64       `json:"currency_pair_id"`
	LastErrorMessage pgtype.Text `json:"last_error_message"`
}

func (q *Queries) RecordFailure(ctx context.Context, arg RecordFailureParams) error {
	_, err := q.db.Exec(ctx, recordFailure, arg.ProviderID, arg.CurrencyPairID, arg.LastErrorMessage)
	return err
}

const recordSuccess = `-- name: RecordSuccess :exec
INSERT INTO provider_health (provider_id, currency_pair_id, last_success_at, consecutive_failures, last_error_message, updated_at)
VALUES ($1, $2, now(), 0, NULL, now())
ON CONFLICT (provider_id, currency_pair_id)
    DO UPDATE SET
                  last_success_at      = now(),
                  consecutive_failures = 0,
                  last_error_message   = NULL,
                  updated_at           = now()
`

type RecordSuccessParams struct {
	ProviderID     int64 `json:"provider_id"`
	CurrencyPairID int64 `json:"currency_pair_id"`
}

func (q *Queries) RecordSuccess(ctx context.Context, arg RecordSuccessParams) error {
	_, err := q.db.Exec(ctx, recordSuccess, arg.ProviderID, arg.CurrencyPairID)
	return err
}

const upsertHealth = `-- name: UpsertHealth :exec
INSERT INTO provider_health (provider_id, currency_pair_id, last_success_at, last_failure_at, consecutive_failures, last_error_message, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (provider_id, currency_pair_id)
    DO UPDATE SET
                  last_success_at      = COALESCE(EXCLUDED.last_success_at, provider_health.last_success_at),
                  last_failure_at      = COALESCE(EXCLUDED.last_failure_at, provider_health.last_failure_at),
                  consecutive_failures = EXCLUDED.consecutive_failures,
                  last_error_message   = EXCLUDED.last_error_message,
                  updated_at           = now()
`

type UpsertHealthParams struct {
	ProviderID          int64              `json:"provider_id"`
	CurrencyPairID      int64              `json:"currency_pair_id"`
	LastSuccessAt       pgtype.Timestamptz `json:"last_success_at"`
	LastFailureAt       pgtype.Timestamptz `json:"last_failure_at"`
	ConsecutiveFailures int32              `json:"consecutive_failures"`
	LastErrorMessage    pgtype.Text        `json:"last_error_message"`
}

func (q *Queries) UpsertHealth(ctx context.Context, arg UpsertHealthParams) error {
	_, err := q.db.Exec(ctx, upsertHealth,
		arg.ProviderID,
		arg.CurrencyPairID,
		arg.LastSuccessAt,
		arg.LastFailureAt,
		arg.ConsecutiveFailures,
		arg.LastErrorMessage,
	)
	return err
}
