// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: providers.sql

package repository

import (
	"context"
)

const getActiveProviders = `-- name: GetActiveProviders :many
SELECT id, name, adapter_type, base_url, rate_json_path, currency_code_mapping, api_key, is_active, created_at, updated_at
FROM providers
WHERE is_active = true
ORDER BY id
`

func (q *Queries) GetActiveProviders(ctx context.Context) ([]Provider, error) {
	rows, err := q.db.Query(ctx, getActiveProviders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Provider{}
	for rows.Next() {
		var i Provider
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AdapterType,
			&i.BaseUrl,
			&i.RateJsonPath,
			&i.CurrencyCodeMapping,
			&i.ApiKey,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderByID = `-- name: GetProviderByID :one
SELECT id, name, adapter_type, base_url, rate_json_path, currency_code_mapping, api_key, is_active, created_at, updated_at
FROM providers
WHERE id = $1
`

func (q *Queries) GetProviderByID(ctx context.Context, id int64) (Provider, error) {
	row := q.db.QueryRow(ctx, getProviderByID, id)
	var i Provider
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.AdapterType,
		&i.BaseUrl,
		&i.RateJsonPath,
		&i.CurrencyCodeMapping,
		&i.ApiKey,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
