// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rates.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getLatestRate = `-- name: GetLatestRate :one
SELECT
    r.id,
    r.currency_pair_id,
    r.source_provider_id,
    r.rate,
    r.is_outdated,
    r.fetched_at,
    r.created_at,
    p.name AS source_provider_name
FROM rates r
         JOIN providers p ON p.id = r.source_provider_id
WHERE r.currency_pair_id = $1
ORDER BY r.fetched_at DESC
LIMIT 1
`

type GetLatestRateRow struct {
	ID                 int64              `json:"id"`
	CurrencyPairID     int64              `json:"currency_pair_id"`
	SourceProviderID   int64              `json:"source_provider_id"`
	Rate               pgtype.Numeric     `json:"rate"`
	IsOutdated         bool               `json:"is_outdated"`
	FetchedAt          pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	SourceProviderName string             `json:"source_provider_name"`
}

func (q *Queries) GetLatestRate(ctx context.Context, currencyPairID int64) (GetLatestRateRow, error) {
	row := q.db.QueryRow(ctx, getLatestRate, currencyPairID)
	var i GetLatestRateRow
	err := row.Scan(
		&i.ID,
		&i.CurrencyPairID,
		&i.SourceProviderID,
		&i.Rate,
		&i.IsOutdated,
		&i.FetchedAt,
		&i.CreatedAt,
		&i.SourceProviderName,
	)
	return i, err
}

const getRateHistory = `-- name: GetRateHistory :many
SELECT
    r.id,
    r.currency_pair_id,
    r.source_provider_id,
    r.rate,
    r.is_outdated,
    r.fetched_at,
    r.created_at,
    p.name AS source_provider_name
FROM rates r
         JOIN providers p ON p.id = r.source_provider_id
WHERE r.currency_pair_id = $1
  AND r.fetched_at >= $2
  AND r.fetched_at <= $3
ORDER BY r.fetched_at ASC
`

type GetRateHistoryParams struct {
	CurrencyPairID int64              `json:"currency_pair_id"`
	FetchedAt      pgtype.Timestamptz `json:"fetched_at"`
	FetchedAt_2    pgtype.Timestamptz `json:"fetched_at_2"`
}

type GetRateHistoryRow struct {
	ID                 int64              `json:"id"`
	CurrencyPairID     int64              `json:"currency_pair_id"`
	SourceProviderID   int64              `json:"source_provider_id"`
	Rate               pgtype.Numeric     `json:"rate"`
	IsOutdated         bool               `json:"is_outdated"`
	FetchedAt          pgtype.Timestamptz `json:"fetched_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	SourceProviderName string             `json:"source_provider_name"`
}

func (q *Queries) GetRateHistory(ctx context.Context, arg GetRateHistoryParams) ([]GetRateHistoryRow, error) {
	rows, err := q.db.Query(ctx, getRateHistory, arg.CurrencyPairID, arg.FetchedAt, arg.FetchedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRateHistoryRow{}
	for rows.Next() {
		var i GetRateHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.CurrencyPairID,
			&i.SourceProviderID,
			&i.Rate,
			&i.IsOutdated,
			&i.FetchedAt,
			&i.CreatedAt,
			&i.SourceProviderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertRate = `-- name: InsertRate :one
INSERT INTO rates (currency_pair_id, source_provider_id, rate, is_outdated, fetched_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, currency_pair_id, source_provider_id, rate, is_outdated, fetched_at, created_at
`

type InsertRateParams struct {
	CurrencyPairID   int64              `json:"currency_pair_id"`
	SourceProviderID int64              `json:"source_provider_id"`
	Rate             pgtype.Numeric     `json:"rate"`
	IsOutdated       bool               `json:"is_outdated"`
	FetchedAt        pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) InsertRate(ctx context.Context, arg InsertRateParams) (Rate, error) {
	row := q.db.QueryRow(ctx, insertRate,
		arg.CurrencyPairID,
		arg.SourceProviderID,
		arg.Rate,
		arg.IsOutdated,
		arg.FetchedAt,
	)
	var i Rate
	err := row.Scan(
		&i.ID,
		&i.CurrencyPairID,
		&i.SourceProviderID,
		&i.Rate,
		&i.IsOutdated,
		&i.FetchedAt,
		&i.CreatedAt,
	)
	return i, err
}

const markOutdated = `-- name: MarkOutdated :exec
UPDATE rates
SET is_outdated = true
WHERE id = (
    SELECT r2.id FROM rates r2
    WHERE r2.currency_pair_id = $1
    ORDER BY r2.fetched_at DESC
    LIMIT 1
)
`

func (q *Queries) MarkOutdated(ctx context.Context, currencyPairID int64) error {
	_, err := q.db.Exec(ctx, markOutdated, currencyPairID)
	return err
}
